### ISSUE TITLE
pip install gridwxcomp error: Could not find module 'geos_c.dll'

### ISSUE THREAD

**Issue by cpearson1** [WSWUP/gridwxcomp#17]
![image](https://user-images.githubusercontent.com/14983120/74881935-0d47ee00-5323-11ea-8cdb-0dce0a0be59c.png)

**Comment by JohnVolk** [comment]
I was able to recreate the same error and solve it on Windows 10. Here's what worked for me:

First remove the gridwxcomp environment:

`$ conda env remove --name gridwxcomp`

clone the GitHub repo:

`$ git clone https://github.com/WSWUP/gridwxcomp.git`

now modify the environment.yml file by removing pip, gridwxcomp, and shapely. In other words your .yml file should look like this:

```
name: gridwxcomp
channels:
  - conda-forge
dependencies:
  - bokeh>=1
  - click>=7
  - fiona>=1.7.13
  - gdal
  - libgdal>=2.3
  - netCDF4
  - numpy>=1.15
  - pandas>=0.24
  - python>=3.7
  - rasterstats>=0.13.0
  - refet>=0.3.7
  - scipy>=1.1.0
  - xarray
  - xlrd>=1.2.0
```

Now install and activate the conda environment:

`$ conda env create -f environment.yml  `
`$ conda activate gridwxcomp`

Next, move to the root directory where you cloned ``gridwxcomp`` and open "setup.py" for editing. In the requires section change the shapely requirement from 'shapely==1.6.4' to 'shapely>=1.6.4'. 

Now install Shapely on its own:

`$ conda install -c conda-forge shapely`

Finally install gridwxcomp in developer mode so that if you need to fiddle with the requirements again you can, from the root directory:

`$ pip install -e .`

For me, on Windows 10, this installed `gdal=3.0.4`, `shapely=1.7.0`, and `fiona=1.8.13` all from the conda-forge channel (this is important, make sure these are installed with conda from that channel).

Because of issues with these inter-dependencies and conflicts between gdal, fiona, and shapely including the one you found it may be difficult to prescribe a standard cross platform conda environment that works for all but this is a step in that direction. These GitHub issue threads may also be helpful: [issue](https://github.com/conda-forge/gdal-feedstock/issues/219#issuecomment-410577468), [issue](https://github.com/conda-forge/fiona-feedstock/issues/89), and [issue](https://github.com/Toblerity/Fiona/issues/402). These posts on stack exchange about the same shapely module geos_c.dll issue (e.g. see [here](https://stackoverflow.com/questions/56813083/oserror-could-not-find-geos-c-dll-or-load-any-of-its-variants), [here](https://stackoverflow.com/questions/52715430/how-do-i-get-geopandas-to-work-on-windows-10-with-winpython), [here](https://stackoverflow.com/questions/12578471/oserror-geos-c-could-not-be-found-when-installing-shapely)) may also be useful. It seems to me that this problem is specific to shapely 1.6.4 and Windows where the c compiler needs to build the .dll file which may require manual installation. In the past on windows however shapely 1.6.4 worked (from conda-forge) but If I can get the same settings that worked now to also work on unix/linux (which the current environment works well for but had issues with newer shapely/gdal versions) I will go ahead and make these changes permanent.

**Comment by cpearson1** [comment]
The above workflow worked with no issues on my Windows 10 PC. 
My env is running gdal=3.0.4, shapely=1.7.0, and fiona=1.8.13.
